spring:
  cloud:
    nacos:
      discovery:
        namespace: e9ddbe41-8a6f-4876-99cb-53b1396d70a6
      config:
        namespace: e9ddbe41-8a6f-4876-99cb-53b1396d70a6
    sentinel:
      transport:
        # port: 9002 # 应用与Sentinel控制台交互的端口，应用本地会起一个该端口占用的HttpServer,可不提供，默认为 8719，若端口冲突会自动向下探测可用的端口。
        dashboard: 127.0.0.1:8849 # Sentinel 控制台地址
      datasource: # 动态数据源支持
        ds1: # ds1, ds2, ds3, ds4 是ReadableDataSource的名字，可随意编写。后面的 file ，zk ，nacos , apollo 就是对应具体的数据源，它们后面的配置就是这些具体数据源各自的配置。
          nacos:
            namespace: ${spring.cloud.nacos.config.namespace}
  datasource:
#    url: 'jdbc:mysql://172.16.3.184:3306/mall?characterEncoding=utf8&connectTimeout=1000&socketTimeout=3000&autoReconnect=true&useUnicode=true&useSSL=false&serverTimezone=Asia/Shanghai'
#    username: test
#    password: test123
    url: 'jdbc:mysql://127.0.0.1:3306/mall?characterEncoding=utf8&connectTimeout=1000&socketTimeout=3000&autoReconnect=true&useUnicode=true&useSSL=false&serverTimezone=Asia/Shanghai'
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      filters: stat
      initial-size: 1 # 初始化时建立物理连接的个数。初始化发生在显示调用init方法，或者第一次getConnection时  生产建议： 15
      max-active: 5 # 最大连接池数量   生产建议：100
      min-idle: 1 # 最小连接池数量 生产建议： 15
      max-wait: 60000 # 程序向连接池中请求连接时,超过maxWait的值后，认为本次请求失败，即连接池
      min-evictable-idle-time-millis: 60000 # 连接保持空闲而不被驱逐的最小时间
      pool-prepared-statements: false # 是否缓存preparedStatement，也就是PSCache。PSCache对支持游标的数据库性能提升巨大，比如说oracle。在mysql下建议关闭。
      test-on-borrow: false # 申请连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能。
      test-on-return: false # 归还连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能。
      test-while-idle: true # 建议配置为true，不影响性能，并且保证安全性。申请连接的时候检测，如果空闲时间大于timeBetweenEvictionRunsMillis，执行validationQuery检测连接是否有效。
      validation-query: select 1 # 测试连接是否可用的SQL语句
#    data:
#      mongodb:
#        host: localhost
#        port: 27017
#        database: mall-port
#  redis:
#    host: 172.16.3.184 # Redis服务器地址
#    database: 0 # Redis数据库索引（默认为0）
#    port: 6379 # Redis服务器连接端口
#    password: redis123 # Redis服务器连接密码（默认为空）
#    timeout: 10000 # 连接超时时间（毫秒）
#    lettuce:
#      pool:
#        max-active: 100 # 连接池最大连接数（使用负值表示没有限制） 默认 8
#        max-wait: -1 # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认 -1
#        max-idle: 35 # 连接池中的最大空闲连接 默认 8
#        min-idle: 5 # 连接池中的最小空闲连接 默认 0
#  rabbitmq:
#      host: 172.16.3.184
#      port: 5672
#      username: test
#      password: test123
seata:
  service:
    grouplist:
      default: 127.0.0.1:8091 # 仅注册中心为file时使用
  enabled: true # 是否启用分布式事务
  registry:
    nacos:
      namespace: ${spring.cloud.nacos.discovery.namespace} # 命名空间的ID
  config:
    nacos:
      namespace: ${spring.cloud.nacos.config.namespace} # 命名空间的ID
